#!/bin/bash

unzip MAIAN.zip 
cd MAIAN-master

python3 -m venv venv 

source venv/bin/activate

pip install --upgrade pip
pip install wheel
pip install web3 z3-solver

# Additional install, cause we need nodejs, and i don`t wanna create another script`
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm install node && nvm use node